/**
 * SiteConfig Interface — Copytier Website Builder
 * Single source of truth for all site.config.ts files.
 * All 8 skill packs read from this structure.
 * Generated by Pack 1 (Strategy & Site Config) from the client Build Brief.
 */

// ─────────────────────────────────────────────────────────────────────────────
// UNION TYPES
// ─────────────────────────────────────────────────────────────────────────────

/** Supported contractor niches (home-service industry) */
export type HomeServiceNicheType =
  | 'plumber'
  | 'hvac'
  | 'electrician'
  | 'roofer'
  | 'landscaper'
  | 'handyman'
  | 'cleaner'
  | 'general-contractor'
  | 'painter'
  | 'pool-spa';

/**
 * NicheType — backward-compatible union.
 * For home-service builds, use one of the HomeServiceNicheType values.
 * For out-of-niche builds, use 'custom' and populate the `industry` config section.
 */
export type NicheType = HomeServiceNicheType | 'custom';

/**
 * schema.org @type value for structured data.
 * For home-service builds: maps 1:1 with HomeServiceNicheType. Used in JSON-LD by Pack 5.
 * For out-of-niche builds: use industry.schemaType (string) for full flexibility.
 * This union covers home-service types. Additional types are supported via
 * the industry.schemaType string field for out-of-niche builds.
 */
export type SchemaOrgType =
  | 'Plumber'
  | 'HVACBusiness'
  | 'Electrician'
  | 'RoofingContractor'
  | 'LandscapingService'
  | 'HomeAndConstructionBusiness'
  | 'HousekeepingService'
  | 'GeneralContractor'
  | 'Painter'
  // Out-of-niche schema types — used when industry.type !== 'home-service'
  | 'ProfessionalService'
  | 'Restaurant'
  | 'Store'
  | 'LegalService'
  | 'AccountingService'
  | 'MedicalBusiness'
  | 'RealEstateAgent'
  | 'NGO'
  | 'Organization';

/** Visitor intent personas. Drives CTA strategy and headline copy. */
export type PersonaType =
  | 'emergency'         // Needs help NOW — burst pipe, no AC in summer, power out
  | 'researcher'        // Comparing options, reading reviews, not yet decided
  | 'price-comparison'  // Actively shopping by price
  | 'returning';        // Past customer coming back or referring

/** CTA button visual variant */
export type CTAVariant = 'primary' | 'secondary' | 'outline' | 'ghost';

/** Build phase — controls which pages and features are deployed */
export type BuildPhase = 'mvp' | 'phase2' | 'phase3';

/** Page types supported by the router and template system */
export type PageType =
  | 'homepage'
  | 'service'
  | 'service-area'
  | 'contact'
  | 'about'
  | 'faq'
  | 'blog'
  | 'blog-post'
  | 'gallery'
  | 'privacy'
  | 'terms'
  | 'financing'
  | 'landing'
  | '404'
  | 'thank-you';

/** HTML input types used in contact form field definitions */
export type FormFieldType =
  | 'text'
  | 'email'
  | 'tel'
  | 'textarea'
  | 'select'
  | 'checkbox'
  | 'radio'
  | 'hidden';

// ─────────────────────────────────────────────────────────────────────────────
// INDUSTRY LAYER (Out-of-Niche Support)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Industry type identifier.
 * 'home-service' = default Copytier contractor flow (uses niche + existing patterns).
 * All other values trigger industry-specific overrides across skills.
 */
export type IndustryType =
  | 'home-service'
  | 'professional-service'
  | 'agency'
  | 'restaurant'
  | 'ecommerce'
  | 'healthcare'
  | 'nonprofit'
  | 'custom';

/**
 * The primary conversion action the site is optimized for.
 * Drives CTA placement, form design, and hero layout across all packs.
 */
export type PrimaryActionType =
  | 'phone'      // Home services, emergency trades — click-to-call dominates
  | 'form'       // General lead gen — contact form is the primary conversion
  | 'booking'    // Restaurants, salons, med spas — reservation/appointment
  | 'meeting'    // B2B professional services — schedule a consultation
  | 'demo'       // SaaS, technology — request a demo
  | 'purchase';  // E-commerce, retail — add to cart / buy now

/**
 * Design aesthetic category.
 * Controls color psychology rules, typography character, spacing density,
 * and imagery treatment across Pack 2 (Design System).
 */
export type DesignStyleType =
  | 'professional-clean'     // B2B services, engineering, consulting — clean grids, muted accents
  | 'bold-creative'          // Agencies, creative studios — strong color, portfolio-forward
  | 'technical-precision'    // Engineering, architecture, manufacturing — structured, data-friendly
  | 'warm-inviting'          // Healthcare, restaurants, nonprofits — approachable, rounded elements
  | 'premium-luxury'         // High-end services, luxury real estate — restrained palette, generous whitespace
  | 'industrial-modern'      // Contractors, construction — the existing Copytier default
  | 'custom';                // Fully custom — all overrides in site.config.ts

/**
 * Conversion configuration for the industry.
 * Replaces the hardcoded contractor CTA patterns with industry-appropriate defaults.
 */
export interface IndustryConversionConfig {
  /** The primary conversion action this site is optimized for */
  primaryAction: PrimaryActionType;
  /** Primary CTA button text, e.g. "Request a Consultation" or "Call Now — 24/7" */
  primaryCTAText: string;
  /** Secondary CTA button text, e.g. "View Our Projects" or "See Our Work" */
  secondaryCTAText: string;
  /** Whether to show the phone number prominently in the header (true for local service, often false for B2B) */
  showPhoneInHeader: boolean;
  /** Whether to show an emergency/urgency banner above navigation (true only for emergency services) */
  showEmergencyBanner: boolean;
  /** Form field names for the primary conversion form. Order matters — fields render in this order. */
  formFields: string[];
}

/**
 * Industry-specific trust signal tiers.
 * Tier 1 = above the fold. Tier 2 = first scroll. Tier 3 = deeper on page.
 * Skills read these to determine what trust elements to place where.
 */
export interface IndustryTrustSignals {
  /** Trust signals displayed above the fold — highest impact, first impression */
  tier1: string[];
  /** Trust signals within the first scroll — builds credibility after initial interest */
  tier2: string[];
  /** Trust signals deeper on page — differentiators for the serious evaluator */
  tier3: string[];
}

/**
 * Industry-specific SEO configuration.
 * Overrides contractor-specific title format and local SEO defaults.
 */
export interface IndustrySEOConfig {
  /**
   * Title tag format template. Use bracket tokens for dynamic replacement.
   * Home-service: "[Service] in [City] | [Company]"
   * B2B/Professional: "[Page] | [Company] — [Tagline]"
   * E-commerce: "[Product] | [Company]"
   */
  titleFormat: string;
  /** Whether local SEO signals are applied (NAP, service areas, LocalBusiness schema) */
  localSEO: boolean;
  /** Whether service area pages are generated (true only for local service businesses) */
  serviceAreaPages: boolean;
}

/**
 * IndustryConfig — the industry layer for out-of-niche builds.
 *
 * When `industry.type` is 'home-service', this section is optional and skills
 * fall through to existing contractor-specific defaults.
 *
 * When `industry.type` is anything else, this section is REQUIRED and overrides
 * contractor-specific behavior in every skill pack.
 *
 * Generated by Pack 1 using data from the industry research process.
 */
export interface IndustryConfig {
  /** Industry identifier — skills read this to select behavior branches */
  type: IndustryType;

  /**
   * schema.org @type for this industry — replaces the hardcoded contractor subtypes.
   * Use the most specific type available.
   * Examples: 'ProfessionalService', 'Restaurant', 'Store', 'LegalService'
   */
  schemaType: string;

  /** Conversion configuration — replaces contractor-specific CTA patterns */
  conversion: IndustryConversionConfig;

  /** Design aesthetic — controls Pack 2 color psychology, typography, and spacing rules */
  designStyle: DesignStyleType;

  /**
   * Ordered list of homepage section component names.
   * Replaces the contractor homepage conversion sequence (Hero → Services → Testimonials → ...).
   * Pack 3 reads this to scaffold the homepage layout.
   * Examples:
   *   B2B: ['hero', 'clientLogos', 'services', 'caseStudy', 'team', 'process', 'cta', 'testimonials', 'faq']
   *   Agency: ['hero', 'resultMetrics', 'portfolio', 'services', 'process', 'team', 'testimonials', 'blog', 'cta']
   *   Restaurant: ['hero', 'menuHighlights', 'about', 'gallery', 'location', 'reviews', 'reservationCTA']
   */
  homepageSections: string[];

  /** Trust signal placement tiers — what appears where on the page */
  trustSignals: IndustryTrustSignals;

  /** SEO configuration — title format, local vs. national, service area page generation */
  seo: IndustrySEOConfig;
}

// ─────────────────────────────────────────────────────────────────────────────
// ADDRESS & GEO
// ─────────────────────────────────────────────────────────────────────────────

/** Physical address. Must match Google Business Profile exactly for NAP consistency. */
export interface AddressConfig {
  /** Street number and name, e.g. "1234 Main St" */
  street: string;
  /** Suite, unit, or apt if applicable */
  suite?: string;
  /** City name */
  city: string;
  /** Two-letter state abbreviation, e.g. "CA" */
  state: string;
  /** 5-digit ZIP code */
  zip: string;
  /** Full country name, e.g. "United States" */
  country: string;
}

/** GPS coordinates for map embeds and LocalBusiness schema */
export interface GeoCoordinates {
  /** Decimal latitude, e.g. 34.0522 */
  latitude: number;
  /** Decimal longitude, e.g. -118.2437 */
  longitude: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// BUSINESS HOURS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Single day hours entry for openingHoursSpec schema property.
 * Uses schema.org DayOfWeek values.
 */
export interface OpeningHoursSpec {
  /** schema.org DayOfWeek URI, e.g. "https://schema.org/Monday" */
  dayOfWeek: string;
  /** 24-hour open time, e.g. "08:00" */
  opens: string;
  /** 24-hour close time, e.g. "17:00" */
  closes: string;
}

/** Business operating hours definition */
export interface HoursConfig {
  /** Human-readable regular hours for display, e.g. "Mon–Fri 8am–6pm" */
  regular: string;
  /** Human-readable emergency/after-hours availability, e.g. "24/7 Emergency Service" */
  emergency: string;
  /** IANA timezone string, e.g. "America/Los_Angeles" */
  timezone: string;
  /** Machine-readable hours array for schema.org LocalBusiness openingHoursSpecification */
  openingHoursSpec: OpeningHoursSpec[];
}

// ─────────────────────────────────────────────────────────────────────────────
// SOCIAL PROFILES
// ─────────────────────────────────────────────────────────────────────────────

/** Social and review platform profile URLs */
export interface SocialConfig {
  /** Full Google Business Profile URL */
  googleBusinessProfile?: string;
  /** Full Facebook page URL */
  facebook?: string;
  /** Full Yelp business page URL */
  yelp?: string;
  /** Full Nextdoor business page URL */
  nextdoor?: string;
  /** Full Instagram profile URL */
  instagram?: string;
  /** Full YouTube channel URL */
  youtube?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// BUSINESS CONFIG
// ─────────────────────────────────────────────────────────────────────────────

/** Core business identity. Maps directly to LocalBusiness schema fields. */
export interface BusinessConfig {
  /** Public-facing business name, e.g. "Mike's Plumbing & Drain" */
  name: string;
  /** Legal registered business name if different from trading name */
  legalName?: string;
  /** Short positioning tagline, max ~10 words. Used in header and schema. */
  tagline: string;
  /** 2–3 sentence business description for About sections and schema description field */
  description: string;
  /** Primary owner or operator name. Used in About page and schema */
  ownerName: string;
  /** Year the business was founded. Used in trust signals and schema foundingDate. */
  yearEstablished: number;
  /** Approximate number of employees. Informational only. */
  employeeCount?: string;
  /** Physical business address. Must match Google Business Profile exactly. */
  address: AddressConfig;
  /** GPS coordinates for map embeds and schema geo property */
  geo: GeoCoordinates;
  /** Operating hours for display and schema */
  hours: HoursConfig;
  /** Social media and review platform links */
  social: SocialConfig;
}

// ─────────────────────────────────────────────────────────────────────────────
// VALUE PROPOSITION & CTAs
// ─────────────────────────────────────────────────────────────────────────────

/** A single call-to-action button definition */
export interface CTAConfig {
  /** Button label text, e.g. "Get a Free Estimate" */
  text: string;
  /** Link destination — can be internal path or tel: link */
  href: string;
  /** Visual style variant controlling Tailwind class selection in Pack 4 */
  variant: CTAVariant;
  /** Optional icon name from the project icon library, e.g. "phone", "calendar" */
  icon?: string;
}

/**
 * Above-the-fold hero value proposition.
 * Drives Pack 4 Hero component and Pack 5 copy generation.
 */
export interface ValueProposition {
  /** Primary hero headline. Max 8 words. Must address the primary persona's #1 job-to-be-done. */
  headline: string;
  /** Supporting subheadline. 15–20 words. Backs up the headline with a concrete benefit or differentiator. */
  subheadline: string;
  /** Primary CTA — the single most important conversion action on the page */
  primaryCTA: CTAConfig;
  /** Secondary CTA — lower-commitment alternative, e.g. "See Our Work" */
  secondaryCTA?: CTAConfig;
}

// ─────────────────────────────────────────────────────────────────────────────
// PERSONAS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Visitor persona configuration.
 * Primary persona controls headline tone and CTA urgency.
 * Secondary persona informs supporting content and FAQs.
 * Used by Pack 5 copy generation prompts.
 */
export interface PersonaConfig {
  /** The dominant visitor intent this site must serve first */
  primary: PersonaType;
  /** The second most common visitor type — informs supporting content */
  secondary: PersonaType;
  /**
   * Niche-specific persona extensions not covered by the four base types.
   * Examples: 'diy-failure', 'property-manager', 'new-homeowner', 'hoa-rep'
   */
  nicheExtensions: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// USER JOURNEYS
// ─────────────────────────────────────────────────────────────────────────────

/** A single touchpoint in a visitor's conversion journey */
export interface JourneyStep {
  /** What the user is doing at this step, e.g. "Lands on homepage from Google search" */
  action: string;
  /** What the user needs at this step to keep moving forward */
  need: string;
  /** The site element that satisfies that need, e.g. "Hero with phone number + trust signals" */
  siteResponse: string;
}

/** Conversion journey for one persona type */
export interface UserJourney {
  /** Which persona this journey maps */
  persona: PersonaType;
  /** Ordered list of touchpoints from arrival to conversion */
  steps: JourneyStep[];
}

/**
 * User journey definitions used by Pack 3 (Architecture) to structure
 * page flow, and by Pack 5 (Content) to ensure copy serves each journey.
 */
export interface UserJourneyConfig {
  /** Journey for the primary persona */
  primary: UserJourney;
  /** Journey for the secondary persona */
  secondary: UserJourney;
}

// ─────────────────────────────────────────────────────────────────────────────
// SUCCESS METRICS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Measurable success targets for this site.
 * Used by Pack 7 (QA & Launch) to configure analytics goals.
 */
export interface SuccessMetrics {
  /** Target conversion rate as a percentage, e.g. 4.5 means 4.5% */
  conversionRateTarget: number;
  /** Target monthly organic search sessions at steady state */
  monthlyOrganicSessionsTarget: number;
  /** Maximum acceptable Largest Contentful Paint in milliseconds */
  lcpTargetMs: number;
  /** Maximum acceptable Time to First Byte in milliseconds */
  ttfbTargetMs: number;
  /** Target Google Business Profile average star rating */
  targetReviewRating: number;
  /** Target number of Google reviews */
  targetReviewCount: number;
  /** Primary conversion event names as logged in GA4 */
  primaryConversionEvents: string[];
  /** Business-specific KPIs beyond standard web metrics */
  businessKPIs?: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// MOSCOW PRIORITIZATION
// ─────────────────────────────────────────────────────────────────────────────

/**
 * MoSCoW feature prioritization for the full site roadmap.
 * Used by Pack 1 to set currentPhase and by Pack 3 to determine which
 * pages and features are built in each phase.
 */
export interface MoSCoWPriority {
  /** Features that MUST be live at MVP launch — non-negotiable */
  mustHave: string[];
  /** Features that SHOULD be included if time permits in phase 2 */
  shouldHave: string[];
  /** Features that COULD be added in phase 3 as enhancements */
  couldHave: string[];
  /** Features explicitly out of scope — documented to prevent scope creep */
  wontHave: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// SERVICES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single service offered by the contractor.
 * Each entry generates a service page (Pack 3), component cards (Pack 4),
 * copy (Pack 5), and a Service schema object (Pack 5).
 */
export interface ServiceConfig {
  /** Display name of the service, e.g. "Water Heater Installation" */
  name: string;
  /** URL-safe slug, e.g. "water-heater-installation". Auto-generates page route. */
  slug: string;
  /** 1–2 sentence description for service cards and meta descriptions */
  shortDescription: string;
  /** Icon identifier from the project icon library, e.g. "wrench", "flame" */
  icon: string;
  /** Whether this service is available 24/7 for emergencies. Triggers emergency UI treatment. */
  isEmergency: boolean;
  /** Customer problem statements this service solves. Used in copy and FAQ generation. */
  problems: string[];
  /** Price range for display, e.g. "$150–$450" or "Free Estimate" */
  priceRange: string;
  /** Seasons when this service is most in demand, e.g. ["summer", "fall"] */
  seasonalRelevance: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// SERVICE AREAS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single geographic area the contractor serves.
 * Each entry with a city type can generate a service-area page (Pack 3).
 * isPrimary city is used in LocalBusiness schema areaServed.
 */
export interface ServiceAreaConfig {
  /** Display name, e.g. "San Diego", "North Park", "San Diego County" */
  name: string;
  /** URL-safe slug, e.g. "san-diego", "north-park" */
  slug: string;
  /** Geographic hierarchy level — drives page template selection in Pack 3 */
  type: 'city' | 'neighborhood' | 'county';
  /** Two-letter state abbreviation, e.g. "CA" */
  state: string;
  /** True for the contractor's primary operating city. Used in homepage copy and schema. */
  isPrimary: boolean;
  /** Optional GPS center point for this area — used in map embeds */
  coordinates?: GeoCoordinates;
}

// ─────────────────────────────────────────────────────────────────────────────
// PAGES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Configuration for a single page.
 * Pack 3 (Architecture) creates the route file; Pack 5 (Content) writes the copy.
 */
export interface PageConfig {
  /** SEO page title. Follow pattern: "[Service] in [City] | [Company Name]" — 50–60 chars */
  title: string;
  /** URL path slug. Homepage is "/", others are e.g. "services/drain-cleaning" */
  slug: string;
  /** Page type — controls which template Pack 3 applies */
  type: PageType;
  /** Meta description for search snippets. 150–160 chars with action CTA. */
  metaDescription: string;
  /** The single H1 for this page. Must be unique across all pages. */
  h1: string;
  /** schema.org @type values to include as JSON-LD on this page */
  includeSchema: string[];
  /** Build phase in which this page is created and deployed */
  phase: BuildPhase;
  /**
   * Ordered list of section component names for the homepage only.
   * Example: ["Hero", "Services", "WhyUs", "Testimonials", "CTA", "FAQ"]
   */
  sections?: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// TRUST SIGNALS
// ─────────────────────────────────────────────────────────────────────────────

/** A professional certification or membership badge */
export interface Certification {
  /** Full name of the certification or membership, e.g. "NATE Certified Technician" */
  name: string;
  /** Optional path to certification logo image, relative to /public */
  logo?: string;
}

/**
 * Trust signals displayed site-wide.
 * Used in hero, footer, contact page, and service pages.
 * High-impact conversion elements — populate all available fields.
 */
export interface TrustSignals {
  /** Average Google review star rating, e.g. 4.9 */
  googleRating: number;
  /** Total number of Google reviews */
  reviewCount: number;
  /** Primary review platform to highlight, e.g. "Google" */
  reviewSource: string;
  /** State contractor license number. Required for California contractors. */
  licenseNumber: string;
  /** License type description, e.g. "C-36 Plumbing Contractor" */
  licenseType: string;
  /** Whether the business is licensed, bonded, AND insured */
  licensedBondedInsured: boolean;
  /** Year business was established. Duplicated here for quick access in trust signal components. */
  yearEstablished: number;
  /** Professional certifications and trade memberships */
  certifications: Certification[];
  /** Service guarantees as display strings, e.g. "100% Satisfaction Guarantee" */
  guarantees: string[];
  /** Whether the business is BBB accredited */
  bbbAccredited: boolean;
  /** BBB letter grade if accredited, e.g. "A+" */
  bbbRating?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// TESTIMONIALS
// ─────────────────────────────────────────────────────────────────────────────

/** A single customer testimonial */
export interface Testimonial {
  /** Customer's first name and last initial, e.g. "Jennifer M." */
  name: string;
  /** City and state, e.g. "San Diego, CA" */
  location: string;
  /** Star rating 1–5 */
  rating: 1 | 2 | 3 | 4 | 5;
  /** Full review text */
  text: string;
  /** Which service this review is about — used for service page testimonial filtering */
  service: string;
  /** Display date, e.g. "March 2024" */
  date: string;
  /** Review platform this came from, e.g. "Google", "Yelp" */
  source: string;
}

/**
 * Testimonial display configuration.
 * Source controls whether reviews render from manual array,
 * Google Places API (Pack 6), or Elfsight widget (Pack 6).
 */
export interface TestimonialConfig {
  /** Where testimonials are loaded from */
  source: 'manual' | 'google-api' | 'elfsight';
  /** How many testimonials to display per page section */
  displayCount: number;
  /** Manually curated testimonials. Required when source is 'manual'. */
  manual: Testimonial[];
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTACT
// ─────────────────────────────────────────────────────────────────────────────

/** Validation rule for a single form field */
export interface FieldValidation {
  /** Minimum character length */
  minLength?: number;
  /** Maximum character length */
  maxLength?: number;
  /** Regex pattern the value must match */
  pattern?: string;
  /** Custom error message shown on validation failure */
  message?: string;
}

/** A single field in the contact form */
export interface FormFieldConfig {
  /** HTML name attribute and Supabase column key */
  name: string;
  /** Human-readable label text */
  label: string;
  /** HTML input type */
  type: FormFieldType;
  /** Whether the field is required */
  required: boolean;
  /** Input placeholder text */
  placeholder?: string;
  /** Options array for select and radio fields */
  options?: string[];
  /** Validation rules applied client-side and server-side */
  validation?: FieldValidation;
}

/**
 * Contact information and form configuration.
 * Used by Pack 4 (form components), Pack 5 (contact page copy),
 * and Pack 6 (Supabase schema + Server Actions).
 */
export interface ContactConfig {
  /** Primary business phone number in display format, e.g. "(619) 555-0100" */
  phone: string;
  /** Phone number formatted for tel: links, e.g. "+16195550100" */
  phoneFormatted: string;
  /** Primary business email address */
  email: string;
  /** After-hours emergency phone if different from primary */
  emergencyPhone?: string;
  /** Business address — typically mirrors BusinessConfig.address */
  address: AddressConfig;
  /** Response time promise shown near the form, e.g. "We respond within 2 hours" */
  responseTimePromise: string;
  /** Ordered field definitions for the contact form */
  formFields: FormFieldConfig[];
  /** Message displayed after successful form submission */
  formSuccessMessage: string;
  /** Message displayed if form submission fails */
  formErrorMessage: string;
  /** Whether to embed a Google Map on the contact page */
  showMap: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// BRANDING
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Color palette. All values should be valid CSS hex codes.
 * Maps to Tailwind CSS custom config generated in Pack 2 (Design System).
 */
export interface ColorConfig {
  /** Primary brand color — used for nav, primary buttons, accents */
  primary: string;
  /** Secondary brand color — used for section backgrounds, secondary UI elements */
  secondary: string;
  /** High-contrast CTA accent color — must pass WCAG AA on both light and dark backgrounds */
  accent: string;
  /** Page background color — typically white or near-white */
  background: string;
  /** Alternate section background for visual rhythm — e.g. very light gray */
  backgroundAlt: string;
  /** Primary body text color */
  text: string;
  /** Muted/secondary text color for captions, labels, helper text */
  textMuted: string;
}

/** Font family configuration */
export interface FontConfig {
  /** Heading font family name — loaded via next/font or Google Fonts */
  heading: string;
  /** Body font family name — optimized for readability at small sizes */
  body: string;
}

/** Logo asset configuration */
export interface LogoConfig {
  /** Path to logo file relative to /public, e.g. "/images/logo.svg" */
  path: string;
  /** Alt text describing the logo for screen readers */
  altText: string;
  /** Intrinsic width in pixels for next/image sizing */
  width: number;
  /** Intrinsic height in pixels for next/image sizing */
  height: number;
}

/** Photography and imagery style guidance for Pack 4 and Pack 5 */
export interface ImageryConfig {
  /** Overall visual tone — controls component layouts and image treatment */
  style: 'professional' | 'friendly' | 'premium';
  /** Whether client has provided real team/technician photos */
  hasTeamPhotos: boolean;
  /** Whether client has provided real before/after or project photos */
  hasProjectPhotos: boolean;
  /** Whether client has provided photos of branded company vehicles */
  hasVehiclePhotos: boolean;
  /** Stock photo search keywords to use as fallback if real photos are unavailable */
  stockPhotoFallback: string;
}

/**
 * Brand identity configuration.
 * Pack 2 reads colors and fonts to generate the Tailwind theme.
 * Pack 4 reads logo and imagery to build components.
 */
export interface BrandingConfig {
  /** Full site color palette */
  colors: ColorConfig;
  /** Typeface selections */
  fonts: FontConfig;
  /** Logo asset details */
  logo: LogoConfig;
  /** Photography style and availability */
  imagery: ImageryConfig;
}

// ─────────────────────────────────────────────────────────────────────────────
// STACK
// ─────────────────────────────────────────────────────────────────────────────

/** Next.js-specific build configuration */
export interface NextJsConfig {
  /** Next.js version semver string, e.g. "14.2.0" */
  version: string;
  /** App Router is always true for Copytier builds */
  router: 'app';
  /** Default rendering strategy for pages */
  rendering: 'SSG' | 'SSR' | 'ISR';
  /** ISR revalidation interval in seconds. Only applies when rendering is 'ISR'. */
  isrRevalidateSeconds?: number;
  /** JavaScript package manager */
  packageManager: 'npm' | 'yarn' | 'pnpm' | 'bun';
  /** Database and auth provider */
  database: 'supabase' | 'prisma' | 'none';
  /** Deployment target */
  deployment: 'vercel' | 'netlify' | 'self-hosted';
  /** CSS framework */
  styling: 'tailwind';
  /** UI component library */
  componentLibrary: 'shadcn' | 'radix' | 'none';
}

/** Email sending and notification configuration */
export interface EmailConfig {
  /** Transactional email provider */
  provider: 'resend' | 'sendgrid' | 'postmark' | 'nodemailer';
  /** Real-time notification service for new lead alerts */
  notificationService: 'slack' | 'email' | 'sms' | 'none';
}

/**
 * Technology stack configuration.
 * Pack 1 sets this; all other packs reference it for code generation decisions.
 */
export interface StackConfig {
  /** CMS/framework platform */
  platform: 'nextjs' | 'wordpress';
  /** Next.js specific configuration. Required when platform is 'nextjs'. */
  nextjs: NextJsConfig;
  /** Primary domain without protocol, e.g. "mikesplumbing.com" */
  domain: string;
  /** Email infrastructure configuration */
  email: EmailConfig;
}

// ─────────────────────────────────────────────────────────────────────────────
// INTEGRATIONS
// ─────────────────────────────────────────────────────────────────────────────

/** Analytics platform configuration */
export interface AnalyticsConfig {
  /** Whether Google Analytics 4 is enabled */
  ga4: boolean;
  /** GA4 Measurement ID, e.g. "G-XXXXXXXXXX". Required when ga4 is true. */
  ga4MeasurementId?: string;
  /** Whether Google Tag Manager is used as the tag container */
  googleTagManager: boolean;
  /** Whether Google Search Console is connected */
  searchConsole: boolean;
}

/** Map embed configuration */
export interface MapsConfig {
  /** Map embed provider */
  provider: 'google' | 'mapbox' | 'none';
  /** Whether to embed a map on the contact page */
  embedOnContact: boolean;
  /** Whether to embed maps on service area pages */
  embedOnServiceAreas: boolean;
}

/** Review platform integration */
export interface ReviewsConfig {
  /** Primary review source to pull from or link to */
  source: 'google' | 'yelp' | 'elfsight' | 'manual';
}

/** Online booking/scheduling integration */
export interface BookingConfig {
  /** Third-party scheduling tool, if any */
  provider: 'calendly' | 'housecall-pro' | 'jobber' | 'servicetitan' | 'none';
  /** Where to embed the booking widget */
  embedLocation: 'contact-page' | 'modal' | 'sidebar' | 'none';
}

/** Live chat integration */
export interface ChatConfig {
  /** Chat widget provider */
  provider: 'tidio' | 'intercom' | 'drift' | 'crisp' | 'none';
  /** Whether to load the chat widget asynchronously to protect LCP score */
  loadAsync: boolean;
}

/** CRM integration */
export interface CRMConfig {
  /** CRM platform receiving new leads from form submissions */
  provider: 'housecall-pro' | 'jobber' | 'servicetitan' | 'hubspot' | 'none';
}

/** Email marketing integration */
export interface EmailMarketingConfig {
  /** Email marketing platform for newsletter/nurture campaigns */
  provider: 'mailchimp' | 'klaviyo' | 'activecampaign' | 'none';
}

/**
 * Third-party integration configuration.
 * Pack 6 (Backend & Integrations) uses this to wire up all external services.
 */
export interface IntegrationConfig {
  /** Web analytics */
  analytics: AnalyticsConfig;
  /** Map embeds */
  maps: MapsConfig;
  /** Review aggregation or display */
  reviews: ReviewsConfig;
  /** Appointment booking */
  booking: BookingConfig;
  /** Live chat widget */
  chat: ChatConfig;
  /** Customer relationship management */
  crm: CRMConfig;
  /** Email marketing and nurture */
  emailMarketing: EmailMarketingConfig;
}

// ─────────────────────────────────────────────────────────────────────────────
// FEATURE FLAGS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Boolean feature flags controlling which optional site capabilities are enabled.
 * Evaluated at build time by Pack 3 (routes), Pack 4 (components), and Pack 6 (backend).
 */
export interface FeatureFlags {
  /** Whether a blog section is included in this build phase */
  blog: boolean;
  /** Whether a standalone FAQ page is generated (distinct from FAQ sections on other pages) */
  faqPage: boolean;
  /** Whether a project gallery page is included */
  galleryPage: boolean;
  /** Whether a financing information page is included */
  financingPage: boolean;
  /** Whether a careers/jobs page is included */
  careersPage: boolean;
  /** Whether video testimonials are embedded (requires YouTube or Vimeo links) */
  videoTestimonials: boolean;
  /** Whether case study pages are included */
  caseStudies: boolean;
  /** Whether a sticky phone + CTA bar appears at the bottom of mobile screens */
  stickyMobileCTA: boolean;
  /** Whether a floating circular phone button appears on mobile (alternative to sticky bar) */
  floatingPhoneButton: boolean;
  /** Whether a site-wide emergency availability banner appears above the nav */
  emergencyBanner: boolean;
  /** Whether the hero image/headline changes seasonally */
  seasonalHero: boolean;
  /** Whether a CCPA cookie consent banner is shown (required for California sites) */
  cookieConsent: boolean;
  /** Whether reCAPTCHA is used on forms (NOTE: honeypot preferred — avoid this) */
  recaptcha: boolean;
  /** Whether a dark mode toggle is included */
  darkMode: boolean;
  /** Whether multi-language support (Spanish) is included */
  multiLanguage: boolean;
  /** Whether honeypot anti-spam fields are included on all forms (always true for production) */
  honeypotField: boolean;
  /** Whether server-side rate limiting is applied to form submission endpoints */
  rateLimiting: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// ROOT CONFIG
// ─────────────────────────────────────────────────────────────────────────────

/**
 * SiteConfig — the complete site configuration interface.
 *
 * This is the SINGLE SOURCE OF TRUTH for every Copytier website build.
 * Generated by Pack 1 from the client Build Brief. Read by all 8 skill packs.
 *
 * File location in each client repo: src/site.config.ts
 *
 * @example
 * import { siteConfig } from '@/site.config';
 * const { business, services } = siteConfig;
 */
export interface SiteConfig {
  /** Core business identity, address, hours, and social profiles */
  business: BusinessConfig;
  /**
   * Contractor niche — controls template selection, icon sets, and copy tone.
   * For home-service builds: use one of the HomeServiceNicheType values.
   * For out-of-niche builds: set to 'custom' and populate the `industry` config.
   */
  niche: NicheType;
  /** schema.org @type for LocalBusiness JSON-LD structured data */
  schemaType: SchemaOrgType;

  /**
   * Industry layer — REQUIRED for out-of-niche builds, OPTIONAL for home-service builds.
   *
   * When niche is a HomeServiceNicheType (plumber, hvac, etc.), this is optional.
   * Skills fall through to existing contractor-specific defaults.
   *
   * When niche is 'custom', this is REQUIRED. Skills read industry.type to determine
   * conversion patterns, design aesthetic, copy tone, section flow, and SEO strategy.
   *
   * Populated by Pack 1 using data from the industry research process.
   */
  industry?: IndustryConfig;
  /** Above-the-fold hero value proposition and primary CTAs */
  valueProposition: ValueProposition;
  /** Visitor persona definitions — drives copy strategy across the site */
  personas: PersonaConfig;
  /** Conversion journey maps per persona — used for page flow and content decisions */
  userJourneys: UserJourneyConfig;
  /** Measurable success targets for analytics and QA sign-off */
  successMetrics: SuccessMetrics;
  /** MoSCoW feature prioritization across the three build phases */
  featurePriority: MoSCoWPriority;
  /** Current active build phase — gates which pages and features are deployed */
  currentPhase: BuildPhase;
  /** All services this contractor offers — each generates a service page */
  services: ServiceConfig[];
  /** All geographic areas served — primary cities generate service-area pages */
  serviceAreas: ServiceAreaConfig[];
  /** All pages in the site across all phases — Pack 3 creates routes from this list */
  pages: PageConfig[];
  /** Conversion trust signals — displayed site-wide in hero, footer, and contact */
  trustSignals: TrustSignals;
  /** Customer testimonials — source controls whether manual, API, or widget */
  testimonials: TestimonialConfig;
  /** Contact information, phone, email, and form configuration */
  contact: ContactConfig;
  /** Brand identity: colors, fonts, logo, and imagery style */
  branding: BrandingConfig;
  /** Technology stack choices — governs all code generation decisions */
  stack: StackConfig;
  /** Third-party integration configuration for analytics, maps, booking, CRM, etc. */
  integrations: IntegrationConfig;
  /** Boolean feature flags for optional site capabilities */
  features: FeatureFlags;
}
